service: vidgen
frameworkVersion: "2"
package:
  exclude:
    - "tests/**"
    - "tests-integration/**"
    - ".idea/**"
    - "serverless-configs/**"
    - "envs/**"
    - "support/**"
    - "node_modules/.cache/**"
    - "scripts/**"
    - ".spago"

provider:
  name: aws
  versionFunctions: false
  region: eu-west-1
  memorySize: 3008

functions:
  vidgen:
    timeout: 60
    handler: vidgen.handler
